### ISSUE TITLE
shellshellshell

### ISSUE THREAD

**Issue by Imtinmin** [De1ta-team/De1CTF2019#6]
搭起来好像没有内网环境

![捕获](https://user-images.githubusercontent.com/38977612/63264390-8b1c3580-c2bd-11e9-9553-56cc6658502f.JPG)

**Comment by Imtinmin** [comment]
docker-compose.yml should be 
```yml
    
version: '2'
services:
  jaivyweb1:
    build: ./jaivyweb1/
    ports:
      - "0.0.0.0:11027:80"
    links:
      - getshell
  getshell: 
    build: ./jaivyweb2/
    tty:
      true
```
